images:
  server:
    name: victor/showcase
    tag: nil
  proxy:
    name: nginx
    tag: 1.17.8-alpine

registry:
  name: nil
  credentials: nil

deployments:
  revisionHistoryLimit: 2
  proxy:
    replicas:
      min: 2
      max: 10
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
      limits:
        cpu: 20m
        memory: 30Mi
  server:
    replicas:
      min: 2
      max: 10
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 256Mi

ingress:
  hosts: []
  middlewares:
    - setFrontHeaders@file

tls:
  dnsNames: []
