version: "3.7"

services:

  app:
    build:
      context: .
      target: development
      args:
        - USER_ID=${UID:-1000}
        - USER_NAME=${USER_NAME:-showcase}
    volumes:
      - sock-app:/run/php
      - .:/var/www
      - ./docker/app/config.development.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini
      - ./docker/app/config.development.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  web:
    image: nginx:alpine
    working_dir: /var/www
    volumes:
      - sock-app:/run/php
      - ./public:/var/www/public
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${WEB_PORT:-80}:80"
    depends_on:
      - app

volumes:
  sock-app:
