version: "3.7"

services:

  app:
    build:
      context: .
      target: development
      args:
        - USER_ID=${UID:-1000}
    volumes:
      - .:/app
      - ./chart/files/app/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./chart/files/app/opcache-development.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./chart/files/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./chart/files/app/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - sock-app:/run/php

  web:
    image: nginx:1.15.12-alpine
    working_dir: /app
    volumes:
      - ./public:/app/public
      - ./chart/files/web/nginx.conf:/etc/nginx/nginx.conf
      - ./chart/files/web/default.conf:/etc/nginx/conf.d/default.conf
      - sock-app:/run/php
    ports:
      - "${WEB_PORT:-80}:3000"
    depends_on:
      - app

volumes:
  sock-app:
