version: "3.3"

services:

    app:
        build: docker/app
        container_name: app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - sock-app:/run/php

    web:
        image: nginx:alpine
        container_name: web
        working_dir: /var/www
        volumes:
            - .:/var/www
            - sock-app:/run/php
            - ./docker/web:/etc/nginx/conf.d
        ports:
            - "80:80"

volumes:
    db:
    sock-app:
