services:
  app:
    build:
      context: .
      target: development
      args:
        USER_ID: ${USER_ID:-1000}
    env_file: .env
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - ${WEB_PORT:-80}:3000
