version: "3.6"

services:

  app:
    build:
      context: .
      dockerfile: docker/app/production/Dockerfile
    volumes:
      - sock-app:/run/php

  web:
    image: nginx:alpine
    volumes:
      - sock-app:/run/php
      - .:/var/www
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${WEB_PORT_H1:-80}:80"

volumes:
  sock-app:
