version: '3.8'

services:

  proxy:
    image: nginx:1.18.0-alpine
    volumes:
      - ./public:/usr/share/nginx/www
      - ./chart/files/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./chart/files/proxy/fastcgi-docker.conf:/etc/nginx/fastcgi.conf
      - ./chart/files/proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${PROXY_PORT:-80}:3000
    depends_on:
      - app

  app:
    build:
      context: .
      target: development
      args:
        - USER_ID=${UID:-1000}
    volumes:
      - .:/var/www/html
      - ./chart/files/server/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./chart/files/server/opcache-development.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./chart/files/server/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./chart/files/server/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
