version: "3.7"

services:

  app:
    build:
      context: .
      target: development
      args:
        - USER_ID=${UID:-1000}
    volumes:
      - .:/app
      - ./docker/app/opcache-development.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - sock-app:/run/php

  web:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ./public:/app/public
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - sock-app:/run/php
    ports:
      - "${WEB_PORT:-80}:80"
    depends_on:
      - app

volumes:
  sock-app:
