kind: ConfigMap
apiVersion: v1

metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}

data: {{ toYaml .Values.config | nindent 2 }}

---

kind: ConfigMap
apiVersion: v1

metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}

data:
  nginx.conf: |-
    {{ .Files.Get "files/web/nginx.conf" | nindent 4 }}

  default.conf: |-
    {{ .Files.Get "files/web/default.conf" | nindent 4 }}
