kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ .Release.Name }}

  minReplicas: {{ .Values.deployment.replicas.min }}
  maxReplicas: {{ .Values.deployment.replicas.max }}

  targetCPUUtilizationPercentage: 90
