{{- range tuple "proxy" "server" }}
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1

metadata:
  name: {{ $.Release.Name }}-{{ . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ . }}

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ $.Release.Name }}-{{ . }}

  minReplicas: {{ index $.Values "deployments" . "replicas" "min" }}
  maxReplicas: {{ index $.Values "deployments" . "replicas" "max" }}

  targetCPUUtilizationPercentage: 90
{{- end }}
