kind: Ingress
apiVersion: extensions/v1beta1

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}

spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: {{ $.Release.Name }}
              servicePort: http
    {{- end }}
