kind: Secret
apiVersion: v1

metadata:
  name: {{ .Release.Name }}-registry
  namespace: {{ .Release.Namespace }}

type: kubernetes.io/dockerconfigjson

stringData:
  .dockerconfigjson: {{ .Values.registry.credentials }}

{{ if .Values.secrets }}
---
kind: Secret
apiVersion: v1

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}

type: Opaque

stringData: {{ toYaml .Values.secrets | nindent 2 }}
{{ end }}
