kind: Service
apiVersion: v1

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}

spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: h2c
      port: {{ .Values.service.port }}
      targetPort: h2c
