kind: Service
apiVersion: v1

metadata:
  name: {package}
  labels:
    app: {package}

spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: {package}
