kind: Service
apiVersion: v1

metadata:
  name: showcase
  labels:
    app: showcase

spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: showcase
